/* automatically generated by rust-bindgen 0.69.5 */

pub type __off_t = ::std::os::raw::c_long;
pub type __off64_t = ::std::os::raw::c_long;
pub type __time_t = ::std::os::raw::c_long;
pub type time_t = __time_t;
pub type FILE = _IO_FILE;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _IO_marker {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _IO_codecvt {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _IO_wide_data {
    _unused: [u8; 0],
}
pub type _IO_lock_t = ::std::os::raw::c_void;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _IO_FILE {
    pub _flags: ::std::os::raw::c_int,
    pub _IO_read_ptr: *mut ::std::os::raw::c_char,
    pub _IO_read_end: *mut ::std::os::raw::c_char,
    pub _IO_read_base: *mut ::std::os::raw::c_char,
    pub _IO_write_base: *mut ::std::os::raw::c_char,
    pub _IO_write_ptr: *mut ::std::os::raw::c_char,
    pub _IO_write_end: *mut ::std::os::raw::c_char,
    pub _IO_buf_base: *mut ::std::os::raw::c_char,
    pub _IO_buf_end: *mut ::std::os::raw::c_char,
    pub _IO_save_base: *mut ::std::os::raw::c_char,
    pub _IO_backup_base: *mut ::std::os::raw::c_char,
    pub _IO_save_end: *mut ::std::os::raw::c_char,
    pub _markers: *mut _IO_marker,
    pub _chain: *mut _IO_FILE,
    pub _fileno: ::std::os::raw::c_int,
    pub _flags2: ::std::os::raw::c_int,
    pub _old_offset: __off_t,
    pub _cur_column: ::std::os::raw::c_ushort,
    pub _vtable_offset: ::std::os::raw::c_schar,
    pub _shortbuf: [::std::os::raw::c_char; 1usize],
    pub _lock: *mut _IO_lock_t,
    pub _offset: __off64_t,
    pub _codecvt: *mut _IO_codecvt,
    pub _wide_data: *mut _IO_wide_data,
    pub _freeres_list: *mut _IO_FILE,
    pub _freeres_buf: *mut ::std::os::raw::c_void,
    pub __pad5: usize,
    pub _mode: ::std::os::raw::c_int,
    pub _unused2: [::std::os::raw::c_char; 20usize],
}
#[test]
fn bindgen_test_layout__IO_FILE() {
    const UNINIT: ::std::mem::MaybeUninit<_IO_FILE> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<_IO_FILE>(),
        216usize,
        concat!("Size of: ", stringify!(_IO_FILE))
    );
    assert_eq!(
        ::std::mem::align_of::<_IO_FILE>(),
        8usize,
        concat!("Alignment of ", stringify!(_IO_FILE))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr)._flags) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(_IO_FILE),
            "::",
            stringify!(_flags)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr)._IO_read_ptr) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(_IO_FILE),
            "::",
            stringify!(_IO_read_ptr)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr)._IO_read_end) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(_IO_FILE),
            "::",
            stringify!(_IO_read_end)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr)._IO_read_base) as usize - ptr as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(_IO_FILE),
            "::",
            stringify!(_IO_read_base)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr)._IO_write_base) as usize - ptr as usize },
        32usize,
        concat!(
            "Offset of field: ",
            stringify!(_IO_FILE),
            "::",
            stringify!(_IO_write_base)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr)._IO_write_ptr) as usize - ptr as usize },
        40usize,
        concat!(
            "Offset of field: ",
            stringify!(_IO_FILE),
            "::",
            stringify!(_IO_write_ptr)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr)._IO_write_end) as usize - ptr as usize },
        48usize,
        concat!(
            "Offset of field: ",
            stringify!(_IO_FILE),
            "::",
            stringify!(_IO_write_end)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr)._IO_buf_base) as usize - ptr as usize },
        56usize,
        concat!(
            "Offset of field: ",
            stringify!(_IO_FILE),
            "::",
            stringify!(_IO_buf_base)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr)._IO_buf_end) as usize - ptr as usize },
        64usize,
        concat!(
            "Offset of field: ",
            stringify!(_IO_FILE),
            "::",
            stringify!(_IO_buf_end)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr)._IO_save_base) as usize - ptr as usize },
        72usize,
        concat!(
            "Offset of field: ",
            stringify!(_IO_FILE),
            "::",
            stringify!(_IO_save_base)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr)._IO_backup_base) as usize - ptr as usize },
        80usize,
        concat!(
            "Offset of field: ",
            stringify!(_IO_FILE),
            "::",
            stringify!(_IO_backup_base)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr)._IO_save_end) as usize - ptr as usize },
        88usize,
        concat!(
            "Offset of field: ",
            stringify!(_IO_FILE),
            "::",
            stringify!(_IO_save_end)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr)._markers) as usize - ptr as usize },
        96usize,
        concat!(
            "Offset of field: ",
            stringify!(_IO_FILE),
            "::",
            stringify!(_markers)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr)._chain) as usize - ptr as usize },
        104usize,
        concat!(
            "Offset of field: ",
            stringify!(_IO_FILE),
            "::",
            stringify!(_chain)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr)._fileno) as usize - ptr as usize },
        112usize,
        concat!(
            "Offset of field: ",
            stringify!(_IO_FILE),
            "::",
            stringify!(_fileno)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr)._flags2) as usize - ptr as usize },
        116usize,
        concat!(
            "Offset of field: ",
            stringify!(_IO_FILE),
            "::",
            stringify!(_flags2)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr)._old_offset) as usize - ptr as usize },
        120usize,
        concat!(
            "Offset of field: ",
            stringify!(_IO_FILE),
            "::",
            stringify!(_old_offset)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr)._cur_column) as usize - ptr as usize },
        128usize,
        concat!(
            "Offset of field: ",
            stringify!(_IO_FILE),
            "::",
            stringify!(_cur_column)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr)._vtable_offset) as usize - ptr as usize },
        130usize,
        concat!(
            "Offset of field: ",
            stringify!(_IO_FILE),
            "::",
            stringify!(_vtable_offset)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr)._shortbuf) as usize - ptr as usize },
        131usize,
        concat!(
            "Offset of field: ",
            stringify!(_IO_FILE),
            "::",
            stringify!(_shortbuf)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr)._lock) as usize - ptr as usize },
        136usize,
        concat!(
            "Offset of field: ",
            stringify!(_IO_FILE),
            "::",
            stringify!(_lock)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr)._offset) as usize - ptr as usize },
        144usize,
        concat!(
            "Offset of field: ",
            stringify!(_IO_FILE),
            "::",
            stringify!(_offset)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr)._codecvt) as usize - ptr as usize },
        152usize,
        concat!(
            "Offset of field: ",
            stringify!(_IO_FILE),
            "::",
            stringify!(_codecvt)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr)._wide_data) as usize - ptr as usize },
        160usize,
        concat!(
            "Offset of field: ",
            stringify!(_IO_FILE),
            "::",
            stringify!(_wide_data)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr)._freeres_list) as usize - ptr as usize },
        168usize,
        concat!(
            "Offset of field: ",
            stringify!(_IO_FILE),
            "::",
            stringify!(_freeres_list)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr)._freeres_buf) as usize - ptr as usize },
        176usize,
        concat!(
            "Offset of field: ",
            stringify!(_IO_FILE),
            "::",
            stringify!(_freeres_buf)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__pad5) as usize - ptr as usize },
        184usize,
        concat!(
            "Offset of field: ",
            stringify!(_IO_FILE),
            "::",
            stringify!(__pad5)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr)._mode) as usize - ptr as usize },
        192usize,
        concat!(
            "Offset of field: ",
            stringify!(_IO_FILE),
            "::",
            stringify!(_mode)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr)._unused2) as usize - ptr as usize },
        196usize,
        concat!(
            "Offset of field: ",
            stringify!(_IO_FILE),
            "::",
            stringify!(_unused2)
        )
    );
}
impl Default for _IO_FILE {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
extern "C" {
    pub fn fclose(__stream: *mut FILE) -> ::std::os::raw::c_int;
}
pub type mz_ulong = ::std::os::raw::c_ulong;
extern "C" {
    pub fn mz_crc32(crc: mz_ulong, ptr: *const ::std::os::raw::c_uchar, buf_len: usize)
        -> mz_ulong;
}
pub type mz_alloc_func = ::std::option::Option<
    unsafe extern "C" fn(
        opaque: *mut ::std::os::raw::c_void,
        items: usize,
        size: usize,
    ) -> *mut ::std::os::raw::c_void,
>;
pub type mz_free_func = ::std::option::Option<
    unsafe extern "C" fn(opaque: *mut ::std::os::raw::c_void, address: *mut ::std::os::raw::c_void),
>;
pub type mz_realloc_func = ::std::option::Option<
    unsafe extern "C" fn(
        opaque: *mut ::std::os::raw::c_void,
        address: *mut ::std::os::raw::c_void,
        items: usize,
        size: usize,
    ) -> *mut ::std::os::raw::c_void,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mz_internal_state {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mz_stream_s {
    pub next_in: *const ::std::os::raw::c_uchar,
    pub avail_in: ::std::os::raw::c_uint,
    pub total_in: mz_ulong,
    pub next_out: *mut ::std::os::raw::c_uchar,
    pub avail_out: ::std::os::raw::c_uint,
    pub total_out: mz_ulong,
    pub msg: *mut ::std::os::raw::c_char,
    pub state: *mut mz_internal_state,
    pub zalloc: mz_alloc_func,
    pub zfree: mz_free_func,
    pub opaque: *mut ::std::os::raw::c_void,
    pub data_type: ::std::os::raw::c_int,
    pub adler: mz_ulong,
    pub reserved: mz_ulong,
}
#[test]
fn bindgen_test_layout_mz_stream_s() {
    const UNINIT: ::std::mem::MaybeUninit<mz_stream_s> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<mz_stream_s>(),
        112usize,
        concat!("Size of: ", stringify!(mz_stream_s))
    );
    assert_eq!(
        ::std::mem::align_of::<mz_stream_s>(),
        8usize,
        concat!("Alignment of ", stringify!(mz_stream_s))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).next_in) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(mz_stream_s),
            "::",
            stringify!(next_in)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).avail_in) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(mz_stream_s),
            "::",
            stringify!(avail_in)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).total_in) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(mz_stream_s),
            "::",
            stringify!(total_in)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).next_out) as usize - ptr as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(mz_stream_s),
            "::",
            stringify!(next_out)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).avail_out) as usize - ptr as usize },
        32usize,
        concat!(
            "Offset of field: ",
            stringify!(mz_stream_s),
            "::",
            stringify!(avail_out)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).total_out) as usize - ptr as usize },
        40usize,
        concat!(
            "Offset of field: ",
            stringify!(mz_stream_s),
            "::",
            stringify!(total_out)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).msg) as usize - ptr as usize },
        48usize,
        concat!(
            "Offset of field: ",
            stringify!(mz_stream_s),
            "::",
            stringify!(msg)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).state) as usize - ptr as usize },
        56usize,
        concat!(
            "Offset of field: ",
            stringify!(mz_stream_s),
            "::",
            stringify!(state)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).zalloc) as usize - ptr as usize },
        64usize,
        concat!(
            "Offset of field: ",
            stringify!(mz_stream_s),
            "::",
            stringify!(zalloc)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).zfree) as usize - ptr as usize },
        72usize,
        concat!(
            "Offset of field: ",
            stringify!(mz_stream_s),
            "::",
            stringify!(zfree)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).opaque) as usize - ptr as usize },
        80usize,
        concat!(
            "Offset of field: ",
            stringify!(mz_stream_s),
            "::",
            stringify!(opaque)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).data_type) as usize - ptr as usize },
        88usize,
        concat!(
            "Offset of field: ",
            stringify!(mz_stream_s),
            "::",
            stringify!(data_type)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).adler) as usize - ptr as usize },
        96usize,
        concat!(
            "Offset of field: ",
            stringify!(mz_stream_s),
            "::",
            stringify!(adler)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).reserved) as usize - ptr as usize },
        104usize,
        concat!(
            "Offset of field: ",
            stringify!(mz_stream_s),
            "::",
            stringify!(reserved)
        )
    );
}
impl Default for mz_stream_s {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type mz_stream = mz_stream_s;
pub type mz_streamp = *mut mz_stream;
extern "C" {
    pub fn mz_deflateInit2(
        pStream: mz_streamp,
        level: ::std::os::raw::c_int,
        method: ::std::os::raw::c_int,
        window_bits: ::std::os::raw::c_int,
        mem_level: ::std::os::raw::c_int,
        strategy: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn mz_deflate(pStream: mz_streamp, flush: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn mz_deflateEnd(pStream: mz_streamp) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn mz_deflateBound(pStream: mz_streamp, source_len: mz_ulong) -> mz_ulong;
}
extern "C" {
    pub fn mz_inflateInit2(
        pStream: mz_streamp,
        window_bits: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn mz_inflate(pStream: mz_streamp, flush: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn mz_inflateEnd(pStream: mz_streamp) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn free(__ptr: *mut ::std::os::raw::c_void);
}
pub type mz_uint16 = ::std::os::raw::c_ushort;
pub type mz_uint32 = ::std::os::raw::c_uint;
pub type mz_uint = ::std::os::raw::c_uint;
pub type mz_uint64 = u64;
pub type mz_bool = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mz_zip_archive_file_stat {
    pub m_file_index: mz_uint32,
    pub m_central_dir_ofs: mz_uint64,
    pub m_version_made_by: mz_uint16,
    pub m_version_needed: mz_uint16,
    pub m_bit_flag: mz_uint16,
    pub m_method: mz_uint16,
    pub m_time: time_t,
    pub m_crc32: mz_uint32,
    pub m_comp_size: mz_uint64,
    pub m_uncomp_size: mz_uint64,
    pub m_internal_attr: mz_uint16,
    pub m_external_attr: mz_uint32,
    pub m_local_header_ofs: mz_uint64,
    pub m_comment_size: mz_uint32,
    pub m_is_directory: mz_bool,
    pub m_is_encrypted: mz_bool,
    pub m_is_supported: mz_bool,
    pub m_filename: [::std::os::raw::c_char; 512usize],
    pub m_comment: [::std::os::raw::c_char; 512usize],
}
#[test]
fn bindgen_test_layout_mz_zip_archive_file_stat() {
    const UNINIT: ::std::mem::MaybeUninit<mz_zip_archive_file_stat> =
        ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<mz_zip_archive_file_stat>(),
        1112usize,
        concat!("Size of: ", stringify!(mz_zip_archive_file_stat))
    );
    assert_eq!(
        ::std::mem::align_of::<mz_zip_archive_file_stat>(),
        8usize,
        concat!("Alignment of ", stringify!(mz_zip_archive_file_stat))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).m_file_index) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(mz_zip_archive_file_stat),
            "::",
            stringify!(m_file_index)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).m_central_dir_ofs) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(mz_zip_archive_file_stat),
            "::",
            stringify!(m_central_dir_ofs)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).m_version_made_by) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(mz_zip_archive_file_stat),
            "::",
            stringify!(m_version_made_by)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).m_version_needed) as usize - ptr as usize },
        18usize,
        concat!(
            "Offset of field: ",
            stringify!(mz_zip_archive_file_stat),
            "::",
            stringify!(m_version_needed)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).m_bit_flag) as usize - ptr as usize },
        20usize,
        concat!(
            "Offset of field: ",
            stringify!(mz_zip_archive_file_stat),
            "::",
            stringify!(m_bit_flag)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).m_method) as usize - ptr as usize },
        22usize,
        concat!(
            "Offset of field: ",
            stringify!(mz_zip_archive_file_stat),
            "::",
            stringify!(m_method)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).m_time) as usize - ptr as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(mz_zip_archive_file_stat),
            "::",
            stringify!(m_time)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).m_crc32) as usize - ptr as usize },
        32usize,
        concat!(
            "Offset of field: ",
            stringify!(mz_zip_archive_file_stat),
            "::",
            stringify!(m_crc32)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).m_comp_size) as usize - ptr as usize },
        40usize,
        concat!(
            "Offset of field: ",
            stringify!(mz_zip_archive_file_stat),
            "::",
            stringify!(m_comp_size)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).m_uncomp_size) as usize - ptr as usize },
        48usize,
        concat!(
            "Offset of field: ",
            stringify!(mz_zip_archive_file_stat),
            "::",
            stringify!(m_uncomp_size)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).m_internal_attr) as usize - ptr as usize },
        56usize,
        concat!(
            "Offset of field: ",
            stringify!(mz_zip_archive_file_stat),
            "::",
            stringify!(m_internal_attr)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).m_external_attr) as usize - ptr as usize },
        60usize,
        concat!(
            "Offset of field: ",
            stringify!(mz_zip_archive_file_stat),
            "::",
            stringify!(m_external_attr)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).m_local_header_ofs) as usize - ptr as usize },
        64usize,
        concat!(
            "Offset of field: ",
            stringify!(mz_zip_archive_file_stat),
            "::",
            stringify!(m_local_header_ofs)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).m_comment_size) as usize - ptr as usize },
        72usize,
        concat!(
            "Offset of field: ",
            stringify!(mz_zip_archive_file_stat),
            "::",
            stringify!(m_comment_size)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).m_is_directory) as usize - ptr as usize },
        76usize,
        concat!(
            "Offset of field: ",
            stringify!(mz_zip_archive_file_stat),
            "::",
            stringify!(m_is_directory)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).m_is_encrypted) as usize - ptr as usize },
        80usize,
        concat!(
            "Offset of field: ",
            stringify!(mz_zip_archive_file_stat),
            "::",
            stringify!(m_is_encrypted)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).m_is_supported) as usize - ptr as usize },
        84usize,
        concat!(
            "Offset of field: ",
            stringify!(mz_zip_archive_file_stat),
            "::",
            stringify!(m_is_supported)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).m_filename) as usize - ptr as usize },
        88usize,
        concat!(
            "Offset of field: ",
            stringify!(mz_zip_archive_file_stat),
            "::",
            stringify!(m_filename)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).m_comment) as usize - ptr as usize },
        600usize,
        concat!(
            "Offset of field: ",
            stringify!(mz_zip_archive_file_stat),
            "::",
            stringify!(m_comment)
        )
    );
}
impl Default for mz_zip_archive_file_stat {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type mz_file_read_func = ::std::option::Option<
    unsafe extern "C" fn(
        pOpaque: *mut ::std::os::raw::c_void,
        file_ofs: mz_uint64,
        pBuf: *mut ::std::os::raw::c_void,
        n: usize,
    ) -> usize,
>;
pub type mz_file_write_func = ::std::option::Option<
    unsafe extern "C" fn(
        pOpaque: *mut ::std::os::raw::c_void,
        file_ofs: mz_uint64,
        pBuf: *const ::std::os::raw::c_void,
        n: usize,
    ) -> usize,
>;
pub type mz_file_needs_keepalive =
    ::std::option::Option<unsafe extern "C" fn(pOpaque: *mut ::std::os::raw::c_void) -> mz_bool>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mz_zip_internal_state_tag {
    _unused: [u8; 0],
}
pub type mz_zip_internal_state = mz_zip_internal_state_tag;
pub const mz_zip_mode_MZ_ZIP_MODE_INVALID: mz_zip_mode = 0;
pub const mz_zip_mode_MZ_ZIP_MODE_READING: mz_zip_mode = 1;
pub const mz_zip_mode_MZ_ZIP_MODE_WRITING: mz_zip_mode = 2;
pub const mz_zip_mode_MZ_ZIP_MODE_WRITING_HAS_BEEN_FINALIZED: mz_zip_mode = 3;
pub type mz_zip_mode = ::std::os::raw::c_uint;
pub const mz_zip_type_MZ_ZIP_TYPE_INVALID: mz_zip_type = 0;
pub const mz_zip_type_MZ_ZIP_TYPE_USER: mz_zip_type = 1;
pub const mz_zip_type_MZ_ZIP_TYPE_MEMORY: mz_zip_type = 2;
pub const mz_zip_type_MZ_ZIP_TYPE_HEAP: mz_zip_type = 3;
pub const mz_zip_type_MZ_ZIP_TYPE_FILE: mz_zip_type = 4;
pub const mz_zip_type_MZ_ZIP_TYPE_CFILE: mz_zip_type = 5;
pub const mz_zip_type_MZ_ZIP_TOTAL_TYPES: mz_zip_type = 6;
pub type mz_zip_type = ::std::os::raw::c_uint;
pub const mz_zip_error_MZ_ZIP_NO_ERROR: mz_zip_error = 0;
pub const mz_zip_error_MZ_ZIP_UNDEFINED_ERROR: mz_zip_error = 1;
pub const mz_zip_error_MZ_ZIP_TOO_MANY_FILES: mz_zip_error = 2;
pub const mz_zip_error_MZ_ZIP_FILE_TOO_LARGE: mz_zip_error = 3;
pub const mz_zip_error_MZ_ZIP_UNSUPPORTED_METHOD: mz_zip_error = 4;
pub const mz_zip_error_MZ_ZIP_UNSUPPORTED_ENCRYPTION: mz_zip_error = 5;
pub const mz_zip_error_MZ_ZIP_UNSUPPORTED_FEATURE: mz_zip_error = 6;
pub const mz_zip_error_MZ_ZIP_FAILED_FINDING_CENTRAL_DIR: mz_zip_error = 7;
pub const mz_zip_error_MZ_ZIP_NOT_AN_ARCHIVE: mz_zip_error = 8;
pub const mz_zip_error_MZ_ZIP_INVALID_HEADER_OR_CORRUPTED: mz_zip_error = 9;
pub const mz_zip_error_MZ_ZIP_UNSUPPORTED_MULTIDISK: mz_zip_error = 10;
pub const mz_zip_error_MZ_ZIP_DECOMPRESSION_FAILED: mz_zip_error = 11;
pub const mz_zip_error_MZ_ZIP_COMPRESSION_FAILED: mz_zip_error = 12;
pub const mz_zip_error_MZ_ZIP_UNEXPECTED_DECOMPRESSED_SIZE: mz_zip_error = 13;
pub const mz_zip_error_MZ_ZIP_CRC_CHECK_FAILED: mz_zip_error = 14;
pub const mz_zip_error_MZ_ZIP_UNSUPPORTED_CDIR_SIZE: mz_zip_error = 15;
pub const mz_zip_error_MZ_ZIP_ALLOC_FAILED: mz_zip_error = 16;
pub const mz_zip_error_MZ_ZIP_FILE_OPEN_FAILED: mz_zip_error = 17;
pub const mz_zip_error_MZ_ZIP_FILE_CREATE_FAILED: mz_zip_error = 18;
pub const mz_zip_error_MZ_ZIP_FILE_WRITE_FAILED: mz_zip_error = 19;
pub const mz_zip_error_MZ_ZIP_FILE_READ_FAILED: mz_zip_error = 20;
pub const mz_zip_error_MZ_ZIP_FILE_CLOSE_FAILED: mz_zip_error = 21;
pub const mz_zip_error_MZ_ZIP_FILE_SEEK_FAILED: mz_zip_error = 22;
pub const mz_zip_error_MZ_ZIP_FILE_STAT_FAILED: mz_zip_error = 23;
pub const mz_zip_error_MZ_ZIP_INVALID_PARAMETER: mz_zip_error = 24;
pub const mz_zip_error_MZ_ZIP_INVALID_FILENAME: mz_zip_error = 25;
pub const mz_zip_error_MZ_ZIP_BUF_TOO_SMALL: mz_zip_error = 26;
pub const mz_zip_error_MZ_ZIP_INTERNAL_ERROR: mz_zip_error = 27;
pub const mz_zip_error_MZ_ZIP_FILE_NOT_FOUND: mz_zip_error = 28;
pub const mz_zip_error_MZ_ZIP_ARCHIVE_TOO_LARGE: mz_zip_error = 29;
pub const mz_zip_error_MZ_ZIP_VALIDATION_FAILED: mz_zip_error = 30;
pub const mz_zip_error_MZ_ZIP_WRITE_CALLBACK_FAILED: mz_zip_error = 31;
pub const mz_zip_error_MZ_ZIP_TOTAL_ERRORS: mz_zip_error = 32;
pub type mz_zip_error = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mz_zip_archive {
    pub m_archive_size: mz_uint64,
    pub m_central_directory_file_ofs: mz_uint64,
    pub m_total_files: mz_uint32,
    pub m_zip_mode: mz_zip_mode,
    pub m_zip_type: mz_zip_type,
    pub m_last_error: mz_zip_error,
    pub m_file_offset_alignment: mz_uint64,
    pub m_pAlloc: mz_alloc_func,
    pub m_pFree: mz_free_func,
    pub m_pRealloc: mz_realloc_func,
    pub m_pAlloc_opaque: *mut ::std::os::raw::c_void,
    pub m_pRead: mz_file_read_func,
    pub m_pWrite: mz_file_write_func,
    pub m_pNeeds_keepalive: mz_file_needs_keepalive,
    pub m_pIO_opaque: *mut ::std::os::raw::c_void,
    pub m_pState: *mut mz_zip_internal_state,
}
#[test]
fn bindgen_test_layout_mz_zip_archive() {
    const UNINIT: ::std::mem::MaybeUninit<mz_zip_archive> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<mz_zip_archive>(),
        112usize,
        concat!("Size of: ", stringify!(mz_zip_archive))
    );
    assert_eq!(
        ::std::mem::align_of::<mz_zip_archive>(),
        8usize,
        concat!("Alignment of ", stringify!(mz_zip_archive))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).m_archive_size) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(mz_zip_archive),
            "::",
            stringify!(m_archive_size)
        )
    );
    assert_eq!(
        unsafe {
            ::std::ptr::addr_of!((*ptr).m_central_directory_file_ofs) as usize - ptr as usize
        },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(mz_zip_archive),
            "::",
            stringify!(m_central_directory_file_ofs)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).m_total_files) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(mz_zip_archive),
            "::",
            stringify!(m_total_files)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).m_zip_mode) as usize - ptr as usize },
        20usize,
        concat!(
            "Offset of field: ",
            stringify!(mz_zip_archive),
            "::",
            stringify!(m_zip_mode)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).m_zip_type) as usize - ptr as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(mz_zip_archive),
            "::",
            stringify!(m_zip_type)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).m_last_error) as usize - ptr as usize },
        28usize,
        concat!(
            "Offset of field: ",
            stringify!(mz_zip_archive),
            "::",
            stringify!(m_last_error)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).m_file_offset_alignment) as usize - ptr as usize },
        32usize,
        concat!(
            "Offset of field: ",
            stringify!(mz_zip_archive),
            "::",
            stringify!(m_file_offset_alignment)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).m_pAlloc) as usize - ptr as usize },
        40usize,
        concat!(
            "Offset of field: ",
            stringify!(mz_zip_archive),
            "::",
            stringify!(m_pAlloc)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).m_pFree) as usize - ptr as usize },
        48usize,
        concat!(
            "Offset of field: ",
            stringify!(mz_zip_archive),
            "::",
            stringify!(m_pFree)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).m_pRealloc) as usize - ptr as usize },
        56usize,
        concat!(
            "Offset of field: ",
            stringify!(mz_zip_archive),
            "::",
            stringify!(m_pRealloc)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).m_pAlloc_opaque) as usize - ptr as usize },
        64usize,
        concat!(
            "Offset of field: ",
            stringify!(mz_zip_archive),
            "::",
            stringify!(m_pAlloc_opaque)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).m_pRead) as usize - ptr as usize },
        72usize,
        concat!(
            "Offset of field: ",
            stringify!(mz_zip_archive),
            "::",
            stringify!(m_pRead)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).m_pWrite) as usize - ptr as usize },
        80usize,
        concat!(
            "Offset of field: ",
            stringify!(mz_zip_archive),
            "::",
            stringify!(m_pWrite)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).m_pNeeds_keepalive) as usize - ptr as usize },
        88usize,
        concat!(
            "Offset of field: ",
            stringify!(mz_zip_archive),
            "::",
            stringify!(m_pNeeds_keepalive)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).m_pIO_opaque) as usize - ptr as usize },
        96usize,
        concat!(
            "Offset of field: ",
            stringify!(mz_zip_archive),
            "::",
            stringify!(m_pIO_opaque)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).m_pState) as usize - ptr as usize },
        104usize,
        concat!(
            "Offset of field: ",
            stringify!(mz_zip_archive),
            "::",
            stringify!(m_pState)
        )
    );
}
impl Default for mz_zip_archive {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
extern "C" {
    pub fn mz_zip_reader_init_file(
        pZip: *mut mz_zip_archive,
        pFilename: *const ::std::os::raw::c_char,
        flags: mz_uint32,
    ) -> mz_bool;
}
extern "C" {
    pub fn mz_zip_reader_init_cfile(
        pZip: *mut mz_zip_archive,
        pFile: *mut FILE,
        archive_size: mz_uint64,
        flags: mz_uint,
    ) -> mz_bool;
}
extern "C" {
    pub fn mz_zip_reader_end(pZip: *mut mz_zip_archive) -> mz_bool;
}
extern "C" {
    pub fn mz_zip_reader_get_num_files(pZip: *mut mz_zip_archive) -> mz_uint;
}
extern "C" {
    pub fn mz_zip_reader_locate_file_v2(
        pZip: *mut mz_zip_archive,
        pName: *const ::std::os::raw::c_char,
        pComment: *const ::std::os::raw::c_char,
        flags: mz_uint,
        file_index: *mut mz_uint32,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn mz_zip_reader_file_stat(
        pZip: *mut mz_zip_archive,
        file_index: mz_uint,
        pStat: *mut mz_zip_archive_file_stat,
    ) -> mz_bool;
}
extern "C" {
    pub fn mz_zip_reader_extract_to_cfile(
        pZip: *mut mz_zip_archive,
        file_index: mz_uint,
        File: *mut FILE,
        flags: mz_uint,
    ) -> mz_bool;
}
extern "C" {
    pub fn mz_zip_writer_init_file(
        pZip: *mut mz_zip_archive,
        pFilename: *const ::std::os::raw::c_char,
        size_to_reserve_at_beginning: mz_uint64,
    ) -> mz_bool;
}
extern "C" {
    pub fn mz_zip_writer_init_cfile(
        pZip: *mut mz_zip_archive,
        pFile: *mut FILE,
        flags: mz_uint,
    ) -> mz_bool;
}
extern "C" {
    pub fn mz_zip_writer_init_from_reader(
        pZip: *mut mz_zip_archive,
        pFilename: *const ::std::os::raw::c_char,
    ) -> mz_bool;
}
extern "C" {
    pub fn mz_zip_writer_add_cfile(
        pZip: *mut mz_zip_archive,
        pArchive_name: *const ::std::os::raw::c_char,
        pSrc_file: *mut FILE,
        size_to_add: mz_uint64,
        pFile_time: *const time_t,
        pComment: *const ::std::os::raw::c_void,
        comment_size: mz_uint16,
        level_and_flags: mz_uint,
        user_extra_data_local: *const ::std::os::raw::c_char,
        user_extra_data_local_len: mz_uint,
        user_extra_data_central: *const ::std::os::raw::c_char,
        user_extra_data_central_len: mz_uint,
    ) -> mz_bool;
}
extern "C" {
    pub fn mz_zip_writer_finalize_archive(pZip: *mut mz_zip_archive) -> mz_bool;
}
extern "C" {
    pub fn mz_zip_writer_end(pZip: *mut mz_zip_archive) -> mz_bool;
}
extern "C" {
    pub fn zip_set_permissions(
        zip_archive: *mut mz_zip_archive,
        file_index: mz_uint,
        filename: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn zip_zip(
        czipfile: *const ::std::os::raw::c_char,
        num_files: ::std::os::raw::c_int,
        ckeys: *mut *const ::std::os::raw::c_char,
        cfiles: *mut *const ::std::os::raw::c_char,
        cdirs: *mut ::std::os::raw::c_int,
        cmtimes: *mut f64,
        compression_level: ::std::os::raw::c_int,
        cappend: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn zip_unzip(
        czipfile: *const ::std::os::raw::c_char,
        cfiles: *mut *const ::std::os::raw::c_char,
        num_files: ::std::os::raw::c_int,
        coverwrite: ::std::os::raw::c_int,
        cjunkpaths: ::std::os::raw::c_int,
        exdir: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn zip_open_utf8(
        filename: *const ::std::os::raw::c_char,
        mode: *const ::std::os::raw::c_char,
        buffer: *mut *mut ::std::os::raw::c_char,
        buffer_size: *mut usize,
    ) -> *mut FILE;
}
extern "C" {
    pub fn zip_file_size(fh: *mut FILE, size: *mut mz_uint64) -> ::std::os::raw::c_int;
}

#[allow(non_camel_case_types)]
pub type zip_char_t = ::std::os::raw::c_char;
